<a href="https://colab.research.google.com/github/carloshilner/carloshilner/blob/main/aula_17_03_2021_HCIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
arr1 = np.random.rand(5)
arr1

array([0.21860232, 0.52583462, 0.72513846, 0.1691371 , 0.50807266])

In [5]:
arr1.max()


0.7251384604790203

In [8]:
arr1.argmax()


SyntaxError: ignored

In [9]:
arr1.min()

0.1691371005935871

In [10]:
arr1.mean()

0.4293570304462369

In [11]:
arr1 + 5 

array([5.21860232, 5.52583462, 5.72513846, 5.1691371 , 5.50807266])

In [13]:
arr2=np.random.rand(5)
arr2

array([0.9546954 , 0.2619079 , 0.1143118 , 0.4568984 , 0.40530761])

In [14]:
arr1+arr2

array([1.17329771, 0.78774252, 0.83945026, 0.6260355 , 0.91338027])

In [15]:
arr1 * arr2

array([0.20869863, 0.13772024, 0.08289188, 0.07727847, 0.20592572])

In [16]:
np.sqrt(arr2)

array([0.97708515, 0.51176939, 0.33810028, 0.6759426 , 0.63663774])

In [17]:
arr2.sum()

2.193121110434188

In [18]:
mat1 = np.random.randint(2,30,(3,2))
mat1

array([[11, 27],
       [21, 23],
       [23, 22]])

In [19]:
mat2 = np.random.randint(5,43,(2,4))
mat2

array([[40, 35, 23, 36],
       [39, 13, 39,  8]])

In [20]:
np.matmul(mat1, mat2)

array([[1493,  736, 1306,  612],
       [1737, 1034, 1380,  940],
       [1778, 1091, 1387, 1004]])

In [23]:
result = np.matmul(mat1,mat2)
result

array([[1493,  736, 1306,  612],
       [1737, 1034, 1380,  940],
       [1778, 1091, 1387, 1004]])

In [24]:
result.sum()

14498

In [26]:
result.sum(axis=0)

array([5008, 2861, 4073, 2556])

In [27]:
result.sum(1)

array([4147, 5091, 5260])

In [ ]:
##indexing e selecting


In [28]:
arr1 = np.arange(2,11)
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr1[2:6]

array([4, 5, 6, 7])

In [30]:
arr1[:6]

array([2, 3, 4, 5, 6, 7])

In [31]:
arr1[3:]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr1[2:5] = 200
arr1

array([  2,   3, 200, 200, 200,   7,   8,   9,  10])

In [35]:
mat1 = np.random.rand(3,2)
mat1

array([[0.09365594, 0.37861327],
       [0.29386513, 0.00603203],
       [0.96544755, 0.76804852]])

In [36]:
mat1[1:,:]

array([[0.29386513, 0.00603203],
       [0.96544755, 0.76804852]])

In [37]:
mat1[1:,:1]

array([[0.29386513],
       [0.96544755]])

In [38]:
## conditional selecting


In [41]:
arr1 = np.arange(2,5)
arr1

array([2, 3, 4])

In [42]:
arr1[[True,False,True]]

array([2, 4])

In [43]:
arr2 = np.random.rand(10)
arr2

array([0.40905981, 0.27758858, 0.58796281, 0.17617023, 0.41852204,
       0.87519271, 0.81270699, 0.98452822, 0.54579099, 0.48879429])

In [44]:
arr2 > 0.5


array([False, False,  True, False, False,  True,  True,  True,  True,
       False])

In [46]:
arr2[arr2>0.5]

array([0.58796281, 0.87519271, 0.81270699, 0.98452822, 0.54579099])